<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/05/09 19:00:01

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'admin',
  'password' => 'mYsEcret',
  'name' => 'doctrine',
)),);
