<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/05/09 17:10:29
sfConfig::add(array(
  'mod_sfjobeetaffiliate_enabled' => true,
  'mod_sfjobeetaffiliate_view_class' => 'sfPHP',
));
