<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/05/09 17:10:30
sfConfig::add(array(
  'mod_sfjobeetlanguage_enabled' => true,
  'mod_sfjobeetlanguage_view_class' => 'sfPHP',
));
