<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/05/06 23:50:58
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 20,
));
