<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/05/09 19:00:00
sfConfig::add(array(
  'mod_sfjobeetlanguage_enabled' => true,
  'mod_sfjobeetlanguage_view_class' => 'sfPHP',
));
